"""BD

Revision ID: 044d6ab61899
Revises: 
Create Date: 2026-04-04 14:28:09.169822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '044d6ab61899'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caja', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuario', ['usuario_creacion'], ['id'])
        batch_op.create_foreign_key(None, 'usuario', ['usuario_movimiento'], ['id'])

    with op.batch_alter_table('insumo', schema=None) as batch_op:
        batch_op.alter_column('foto',
               existing_type=sa.BLOB(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('inventario_insumo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_insumo'))
        batch_op.create_unique_constraint('uq_insumo_sucursal', ['fk_insumo', 'fk_sucursal'])

    with op.batch_alter_table('inventario_producto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_producto'))
        batch_op.create_unique_constraint('uq_producto_sucursal', ['fk_producto', 'fk_sucursal'])

    with op.batch_alter_table('metodo_pago', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuario', ['usuario_movimiento'], ['id'])

    with op.batch_alter_table('pedido_detalle', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuario', ['usuario_movimiento'], ['id'])

    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.alter_column('foto',
               existing_type=sa.BLOB(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('produccion_detalle', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'solicitud_produccion', ['fk_solicitud'], ['id'])

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('foto',
               existing_type=sa.BLOB(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('intentos_fallidos',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('forzar_cambio_clave',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('usuario_otp', schema=None) as batch_op:
        batch_op.alter_column('utilizado',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuario', ['usuario_movimiento'], ['id'])

    with op.batch_alter_table('venta_detalle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_venta'))
        batch_op.create_unique_constraint('uq_venta_producto', ['fk_venta', 'fk_producto'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta_detalle', schema=None) as batch_op:
        batch_op.drop_constraint('uq_venta_producto', type_='unique')
        batch_op.create_index(batch_op.f('fk_venta'), ['fk_venta', 'fk_producto'], unique=True)

    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('usuario_otp', schema=None) as batch_op:
        batch_op.alter_column('utilizado',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(unsigned=True),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('forzar_cambio_clave',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(unsigned=True),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('intentos_fallidos',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(unsigned=True),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('foto',
               existing_type=sa.Text(),
               type_=sa.BLOB(),
               existing_nullable=True)

    with op.batch_alter_table('produccion_detalle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.alter_column('foto',
               existing_type=sa.Text(),
               type_=sa.BLOB(),
               existing_nullable=True)

    with op.batch_alter_table('pedido_detalle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('metodo_pago', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('inventario_producto', schema=None) as batch_op:
        batch_op.drop_constraint('uq_producto_sucursal', type_='unique')
        batch_op.create_index(batch_op.f('fk_producto'), ['fk_producto', 'fk_sucursal'], unique=True)

    with op.batch_alter_table('inventario_insumo', schema=None) as batch_op:
        batch_op.drop_constraint('uq_insumo_sucursal', type_='unique')
        batch_op.create_index(batch_op.f('fk_insumo'), ['fk_insumo', 'fk_sucursal'], unique=True)

    with op.batch_alter_table('insumo', schema=None) as batch_op:
        batch_op.alter_column('foto',
               existing_type=sa.Text(),
               type_=sa.BLOB(),
               existing_nullable=True)

    with op.batch_alter_table('caja', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
